--- # Loop Playbook

- hosts: webclient
  user: ansible
  become: yes
  gather_facts: no
  tasks:
  - name: Add a List of Users
    user: name={{ item }} state=present
    with_items:
      - user1
      - user2
      - user3
