--- # Prompt Playbook for Ansible
- hosts: _local
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: Package to Install?
      default: telnet
      private: no
  tasks:
    - name: Install {{pkg_name}}
      yum: name={{pkg_name}} state=latest
