--- # Start At Playbook for Ansible
# ansible-playbook startat.yml --start-at-task="Install Lynx Web Browser"
# ansible-playbook startat.yml --step
- hosts: local
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install Telnet
    yum: pkg=telnet state=latest
  - name: Install Lynx Web Browser
    yum: pkg=lynx state=latest
  - name: List Home
    command: ls -la /home/ansible
    register: ls_result
  - debug: var=ls_result
