--- # Outline to Playbook Translation

- hosts: webclient
  user: ansible
  become: yes
  gather_facts: no
  
  tasks:
  - name: Playbook Start Timestamp
    command: /usr/bin/date
    register: playbook_start
  - debug: var=playbook_start
  - name: Install Apache Web Server
    yum: name=httpd state=latest
    notify: Restart httpd
  - name: Check Web Server is Running
    command: systemctl status httpd
    register: check_httpd
  - debug: var=check_httpd
  - name: Install Telnet
    yum: name=telnet state=latest
  - name: Install Lynx
    yum: name=lynx state=latest
  - name: Log Packages Installed
    command: yum list installed
    register: packages_installed
  - debug: var=packages_installed
  - name: Playbook End Timestamp
    command: /usr/bin/date
    register: playbook_end
  - debug: var=playbook_end
  handlers:
  - name: Restart httpd
    service: name=httpd state=restarted